name: Run autotests



on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: select teststo run
        required: true
        type: choice
        default: all
        options:
          - all
